# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vector_store_pb2 as vector__store__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vector_store_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upsert = channel.unary_unary(
                '/VectorStore/Upsert',
                request_serializer=vector__store__pb2.UpsertRequest.SerializeToString,
                response_deserializer=vector__store__pb2.UpsertResponse.FromString,
                _registered_method=True)
        self.UpsertBatch = channel.unary_unary(
                '/VectorStore/UpsertBatch',
                request_serializer=vector__store__pb2.UpsertBatchRequest.SerializeToString,
                response_deserializer=vector__store__pb2.UpsertBatchResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/VectorStore/Search',
                request_serializer=vector__store__pb2.SearchRequest.SerializeToString,
                response_deserializer=vector__store__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Count = channel.unary_unary(
                '/VectorStore/Count',
                request_serializer=vector__store__pb2.CountRequest.SerializeToString,
                response_deserializer=vector__store__pb2.CountResponse.FromString,
                _registered_method=True)
        self.Dump = channel.unary_stream(
                '/VectorStore/Dump',
                request_serializer=vector__store__pb2.DumpRequest.SerializeToString,
                response_deserializer=vector__store__pb2.DumpItem.FromString,
                _registered_method=True)


class VectorStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Upsert(self, request, context):
        """Client sends ID and text; Server returns status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertBatch(self, request, context):
        """Client sends batch of items; Server returns statuses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Client sends query string; Server returns top_k strings
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Count(self, request, context):
        """Returns the number of items stored on this node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dump(self, request, context):
        """Streams all locally stored items whose key hash falls in [start_hash, end_hash).
        Used by recovering shards during state transfer. Coordinator does not implement this.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upsert': grpc.unary_unary_rpc_method_handler(
                    servicer.Upsert,
                    request_deserializer=vector__store__pb2.UpsertRequest.FromString,
                    response_serializer=vector__store__pb2.UpsertResponse.SerializeToString,
            ),
            'UpsertBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertBatch,
                    request_deserializer=vector__store__pb2.UpsertBatchRequest.FromString,
                    response_serializer=vector__store__pb2.UpsertBatchResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=vector__store__pb2.SearchRequest.FromString,
                    response_serializer=vector__store__pb2.SearchResponse.SerializeToString,
            ),
            'Count': grpc.unary_unary_rpc_method_handler(
                    servicer.Count,
                    request_deserializer=vector__store__pb2.CountRequest.FromString,
                    response_serializer=vector__store__pb2.CountResponse.SerializeToString,
            ),
            'Dump': grpc.unary_stream_rpc_method_handler(
                    servicer.Dump,
                    request_deserializer=vector__store__pb2.DumpRequest.FromString,
                    response_serializer=vector__store__pb2.DumpItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VectorStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('VectorStore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Upsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorStore/Upsert',
            vector__store__pb2.UpsertRequest.SerializeToString,
            vector__store__pb2.UpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorStore/UpsertBatch',
            vector__store__pb2.UpsertBatchRequest.SerializeToString,
            vector__store__pb2.UpsertBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorStore/Search',
            vector__store__pb2.SearchRequest.SerializeToString,
            vector__store__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Count(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/VectorStore/Count',
            vector__store__pb2.CountRequest.SerializeToString,
            vector__store__pb2.CountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/VectorStore/Dump',
            vector__store__pb2.DumpRequest.SerializeToString,
            vector__store__pb2.DumpItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorControlStub(object):
    """-- Coordinator control (coordinator only, not exposed on shards) --
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/CoordinatorControl/RegisterNode',
                request_serializer=vector__store__pb2.NodeRequest.SerializeToString,
                response_deserializer=vector__store__pb2.NodeResponse.FromString,
                _registered_method=True)
        self.DeregisterNode = channel.unary_unary(
                '/CoordinatorControl/DeregisterNode',
                request_serializer=vector__store__pb2.NodeRequest.SerializeToString,
                response_deserializer=vector__store__pb2.NodeResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/CoordinatorControl/Heartbeat',
                request_serializer=vector__store__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=vector__store__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetPeers = channel.unary_unary(
                '/CoordinatorControl/GetPeers',
                request_serializer=vector__store__pb2.GetPeersRequest.SerializeToString,
                response_deserializer=vector__store__pb2.GetPeersResponse.FromString,
                _registered_method=True)


class CoordinatorControlServicer(object):
    """-- Coordinator control (coordinator only, not exposed on shards) --
    """

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=vector__store__pb2.NodeRequest.FromString,
                    response_serializer=vector__store__pb2.NodeResponse.SerializeToString,
            ),
            'DeregisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterNode,
                    request_deserializer=vector__store__pb2.NodeRequest.FromString,
                    response_serializer=vector__store__pb2.NodeResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=vector__store__pb2.HeartbeatRequest.FromString,
                    response_serializer=vector__store__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeers,
                    request_deserializer=vector__store__pb2.GetPeersRequest.FromString,
                    response_serializer=vector__store__pb2.GetPeersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CoordinatorControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CoordinatorControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorControl(object):
    """-- Coordinator control (coordinator only, not exposed on shards) --
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoordinatorControl/RegisterNode',
            vector__store__pb2.NodeRequest.SerializeToString,
            vector__store__pb2.NodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoordinatorControl/DeregisterNode',
            vector__store__pb2.NodeRequest.SerializeToString,
            vector__store__pb2.NodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoordinatorControl/Heartbeat',
            vector__store__pb2.HeartbeatRequest.SerializeToString,
            vector__store__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CoordinatorControl/GetPeers',
            vector__store__pb2.GetPeersRequest.SerializeToString,
            vector__store__pb2.GetPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
